## Camera Calibration

<p style='direction:rtl; text-align: right'>
برای پیدا کردن ماتریس کالیبراسیون، ابتدا با تابع findChessboardCorners به ازای هر عکس مختصات دو بعدی گوشه‌های صفحه شطرنجی
را به دست می‌آوریم و با تابع cornerSubPix نیز آن‌را ریفاین می‌کنیم. سپس با مختصات سه بعدی آن‌ها که به بر اساس ساختار صفحه
تولید شده‌است، متناظر می‌کنیم. پس از آن، برای این نقاط متناظر شده، با تابع calibrateCamera یک ماتریس کالیبراسیون دوربین به دست می‌آوریم.
<br>
<br>
توجه کنید که مختصات سه بعدی نقاط را در فضا ثابت در نظر می‌گیریم و فرض می‌کنیم دوربین نسبت به صفحه جا به جایی داشته‌است.
پس این نقاط سه بعدی را روی صفحه Z=0 در نظر میگیریم و روی جدولی با مربع‌های ۲۲میلی‌متری قرار می‌دهیم. (گرچه طول ضلع مربع‌ها
اهمیت خاصی ندارد و در نهایت بی‌تاثیر می‌شود)
</p>

In [1]:
import cv2 as cv
import numpy as np
import glob

all_images = []
image_names = glob.glob('./data/hw2/checkerboard/*.jpg')
for image_name in sorted(image_names):
    all_images.append(cv.imread(image_name))


In [2]:
def get_camera_matrix(images, calibration_flags=None):
    board_size = (6, 9)

    pts2d = []
    pts3d = np.zeros((len(images), board_size[0] * board_size[1], 3), np.float32)
    pts3d[:, :, :2] = np.mgrid[0:board_size[0], 0:board_size[1]].T.reshape(-1, 2) * 0.022
    pts3d = list(pts3d)

    for img in images:
        img_gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
        ret, corners = cv.findChessboardCorners(img_gray, board_size,
                                                cv.CALIB_CB_ADAPTIVE_THRESH |
                                                cv.CALIB_CB_FAST_CHECK |
                                                cv.CALIB_CB_NORMALIZE_IMAGE)
        corners2 = cv.cornerSubPix(img_gray, corners, (11, 11), (-1, -1),
                                   (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 50, 0.0001))
        pts2d.append(corners2)

    ret, mtx, dis, rs, ts = cv.calibrateCamera(pts3d, pts2d, images[0].shape[:2][::-1], None, None,
                                               flags=calibration_flags)
    return mtx


mat1 = get_camera_matrix(all_images[0:10])
print(f'1: {mat1}')
mat2 = get_camera_matrix(all_images[5:15])
print(f'2: {mat2}')
mat3 = get_camera_matrix(all_images[10:20])
print(f'3: {mat3}')
mat4 = get_camera_matrix(all_images[0:20])
print(f'4: {mat4}')

1: [[2.93177397e+03 0.00000000e+00 9.11528486e+02]
 [0.00000000e+00 2.95269008e+03 5.51573019e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
2: [[3.00242712e+03 0.00000000e+00 8.84364854e+02]
 [0.00000000e+00 2.99849267e+03 5.36366749e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
3: [[3.04620076e+03 0.00000000e+00 7.18345156e+02]
 [0.00000000e+00 3.03488234e+03 5.48592630e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
4: [[2.98242750e+03 0.00000000e+00 8.34070879e+02]
 [0.00000000e+00 2.99043400e+03 5.14527833e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]


<p style='direction:rtl; text-align: right'>
همانطور که در بالاتر مشاهده می‌کنید، ماتریس‌های به دست آمده در شرایط مختلف تقریبا یکسان است و خطای نسبی آن‌ها را در ادامه
می‌توانید مشاهده کنید.
<br>
خطای موجود می‌تواند به دلیل وجود دیستورشن‌هایی در تصویر برداری باشد که در مدل‌سازی ما جای‌ ندارد. به علاوه، خطای عددی نیز سهم
زیادی می‌تواند داشته باشد زیرا محاسبات با float32 انجام شده‌است.
</p>



In [3]:
mats = [mat1, mat2, mat3, mat4]
dists = np.zeros((len(mats), len(mats)))

for i, matA in enumerate(mats):
    for j, matB in enumerate(mats):
        dists[i, j] = np.linalg.norm(matA - matB) / np.linalg.norm(matA)

print(dists)

[[0.         0.02090029 0.05567106 0.02481711]
 [0.02055419 0.         0.04028199 0.01349004]
 [0.05441994 0.04003975 0.         0.03266112]
 [0.02458553 0.01358919 0.03310022 0.        ]]


<p style='direction:rtl; text-align: right'>
فاصله‌ کانونی دوربین را بر اساس ماتریس به دست آمده از همه عکس‌ها و با اعمال فرض‌های وسط بودن پرینسیپال پوینت و مربعی بودن پیکسل‌ها حساب می‌کنیم.
با فرض مربعی بودن پیکسل‌ها، درایه اول ماتریس کالیبراسیون را به عنوان فاصله کانونی در نظر می‌گیریم.
</p>

In [4]:
mat = get_camera_matrix(all_images[0:20],
                        calibration_flags=cv.CALIB_FIX_ASPECT_RATIO | cv.CALIB_FIX_PRINCIPAL_POINT)
print(f'Focal Distance = {mat[0, 0]:.2f}px')


Focal Distance = 3005.14px
